name: Build, Push, and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    name: Build and push to Docker Hub
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: tawadeshubham16/portfolio
      STACK_NAME: portfolio
      REMOTE_STACK_PATH: /home/${{ secrets.DEPLOY_USER }}/deploy/infra/swarm/website-stack.yml
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker buildx build \
            --load \
            --tag "${DOCKER_IMAGE}:latest" \
            --tag "${DOCKER_IMAGE}:${IMAGE_TAG}" \
            -f Dockerfile \
            .

      - name: Publish Docker Image to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "${DOCKERHUB_TOKEN}" | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
          docker push "${DOCKER_IMAGE}:latest"
          docker push "${DOCKER_IMAGE}:${IMAGE_TAG}"

      - name: Deploy latest Docker image to Docker Swarm
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            set -eu
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            docker pull "${{ env.DOCKER_IMAGE }}:${{ env.IMAGE_TAG }}"
            export WEBSITE_IMAGE_TAG="${{ env.IMAGE_TAG }}"
            docker stack deploy --with-registry-auth -c "${{ env.REMOTE_STACK_PATH }}" "${{ env.STACK_NAME }}"
