name: Build, Push, and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    name: Build and push to Docker Hub
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: tawadeshubham16/portfolio
      STACK_NAME: portfolio
      REMOTE_STACK_PATH: /home/${{ secrets.DEPLOY_USER }}/website-stack.yml

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

      - name: Redeploy Docker Swarm stack
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            set -eu
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            docker pull "${{ env.DOCKER_IMAGE }}:latest"
            docker stack deploy --with-registry-auth -c "${{ env.REMOTE_STACK_PATH }}" "${{ env.STACK_NAME }}"
